# Generated by Django 5.2.6 on 2025-09-22 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userfollows", "0003_userblock_created_at_alter_userblock_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfollows",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
