# Generated by Django 5.2.6 on 2025-09-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('BOOK', 'Livre'), ('ARTICLE', 'Article')], default='BOOK', max_length=10),
        ),
    ]
