# Generated by Django 5.0 on 2025-09-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('', 'Choisissez un type'), ('BOOK', 'Livre'), ('ARTICLE', 'Article')], max_length=10),
        ),
    ]
